# Generated by Django 2.2.16 on 2023-03-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20230320_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Download the image.', upload_to='posts/', verbose_name='image'),
        ),
    ]
