# Generated by Django 2.2.16 on 2023-03-27 16:17

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20230327_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Напишите Ваш комментарий.', max_length=200, validators=[posts.validators.validate_not_empty]),
        ),
    ]
